# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode8
language: objective-c
# cache: cocoapods
# podfile: Example/Podfile
# before_install:
# - gem install cocoapods # Since Travis is not always on latest version
# - pod install --project-directory=Example
before_install:
- gem install cocoapods --pre --no-rdoc --no-ri --no-document --quiet
- pod repo update
script:
#- set -o pipefail && xcodebuild test -workspace Example/Aria2.xcworkspace -scheme Aria2-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- xcodebuild -version
- xcodebuild -showsdks
- xcodebuild -workspace Example/Aria2.xcworkspace -scheme Aria2-Example -sdk iphonesimulator9.3 ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
